name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'
      
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      
      - name: Lint code
        run: yarn lint
      
      - name: Type check
        run: yarn check-types
      
      - name: Build extension
        run: yarn compile
      
      - name: Run tests
        run: |
          xvfb-run -a yarn test
        env:
          DISPLAY: ':99.0'
      
      - name: Package extension (test)
        run: |
          npm install -g @vscode/vsce
          vsce package --no-dependencies
      
      - name: Upload test artifacts
        uses: actions/upload-artifact@v4
        with:
          name: extension-package-${{ github.sha }}
          path: '*.vsix'
          retention-days: 7

  security:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'
      
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      
      - name: Run security audit
        run: yarn audit --level moderate
        continue-on-error: true
